matrix:
  include:
    - language: node_js
      node_js: 
        - "stable"
      cache:
        directories:
         - node_modules
      before_script:
        - cd frontend/todo-app
      script:
        - npm test
        - npm run-script build

    - language: java
      openjdk:
        - openjdk8
      before_script:
        - cd restful-web-services/
      script:
        - mvn verify -Dmaven.test.skip=true

  deploy:
     provider: gae
     keyfile: high5softwarept-2aa3c2c661d2.json
     project: high5softwarept
     on: trial-deploy


