services:
  - docker

before_install:
  - docker build -t high5app .
  - docker ps -a
  - docker run high5
  - docker ps -a

deploy:
  provider: gae
  keyfile: high5softwarept-2aa3c2c661d2.json
  project: high5softwarept


