language:
  - java

services:
  - docker

before_install:
  - docker build -t high5app .
  - docker run -d high5app

install:
  - docker ps | grep -q high5app

deploy:
  provider: gae
  keyfile: high5softwarept-2aa3c2c661d2.json
  project: high5softwarept


