matrix:
  include:
    - language: node_js
      node_js: 
        - "stable"
      cache:
        directories:
         - node_modules
      before_script:
        - cd frontend/todo-app
      script:
        - npm test
        - npm run-scripts build

    - language: java
      openjdk:
        - openjdk8
  



