sudo: false

language:
  - minimal

services:
  - docker

before_install:
  - docker build -t high5app .
  - docker run -d high5app

install:
  - docker ps | grep -q high5app

deploy:
  provider: gae
  keyfile: credentials.tar.gz.enc
  project: high5serviceaccount
  skip-cleanup: true
  on:
    branch: development


