version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: restful-web-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always   
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-client:
    build:
      context: frontend/todo-app
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://172.17.0.2:4200
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:   